-- ============================================================
-- Module : main
-- ============================================================
-- Ce module ne possède pas de tables propres.
-- Les langues du système sont gérées dans le module lang.
-- Voir : module/lang/database/lang.sql
-- ============================================================
